*graph on ln_kldexp - hungary
*twoway (scatter ln_kldexp ln_good_total if year == 2015 & iso3_o == "HUN", mcolor(black) msymbol(circle) mlabel(iso3_d)) (scatter ln_kldexp ln_good_total if year == 2016 & iso3_o == "HUN", mcolor(black) msymbol(square) mlabel(iso3_d)) (scatter ln_kldexp ln_good_total if year == 2017 & iso3_o == "HUN", mcolor(black) msymbol(triangle) mlabel(iso3_d)), legend(lab(1 "2015") lab(2 "2016") lab( 3 "2017")) graphregion(color(white))

*graph on ln_kldexp 1 - Hungary
twoway (scatter ln_kldexp ln_good_total if year == 2015 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(circle)) (scatter ln_kldexp ln_good_total if year == 2016 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(square)) (scatter ln_kldexp ln_good_total if year == 2017 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(triangle)) (scatter ln_kldexp ln_good_total if year == 2015 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(circle)) (scatter ln_kldexp ln_good_total if year == 2016 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(square)) (scatter ln_kldexp ln_good_total if year == 2017 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(triangle)), legend(lab(1 "EU - 2015") lab(2 "EU - 2016") lab( 3 "EU - 2017") lab(4 "not EU - 2015") lab(5 "not EU - 2016") lab(6 "not EU - 2017")) graphregion(color(white)) ytitle("") xtitle("") title("Exporter KLD (ln) and trade volume (ln) - HUN")
graph export "output/graph_good_total.png", replace

*graph on ln_kldexp 2 - Hungary
twoway (scatter ln_kldexp ln_distw if year == 2015 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(circle)) (scatter ln_kldexp ln_distw if year == 2016 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(square)) (scatter ln_kldexp ln_distw if year == 2017 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(triangle)) (scatter ln_kldexp ln_distw if year == 2015 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(circle)) (scatter ln_kldexp ln_distw if year == 2016 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(square)) (scatter ln_kldexp ln_distw if year == 2017 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(triangle)), legend(lab(1 "EU - 2015") lab(2 "EU - 2016") lab( 3 "EU - 2017") lab(4 "not EU - 2015") lab(5 "not EU - 2016") lab(6 "not EU - 2017")) graphregion(color(white)) ytitle("") xtitle("") title("Exporter KLD (ln) and distance to importer (ln) - HUN")
graph export "output/graph_distw.png", replace

*graph on ln_kldexp 3 - Hungary
twoway (scatter ln_kldexp ln_gdp_d if year == 2015 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(circle)) (scatter ln_kldexp ln_gdp_d if year == 2016 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(square)) (scatter ln_kldexp ln_gdp_d if year == 2017 & iso3_o == "HUN" & eu_relation_importer == "EU", mcolor(blue) msymbol(triangle)) (scatter ln_kldexp ln_gdp_d if year == 2015 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(circle)) (scatter ln_kldexp ln_gdp_d if year == 2016 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(square)) (scatter ln_kldexp ln_gdp_d if year == 2017 & iso3_o == "HUN" & eu_relation_importer != "EU", mcolor(red) msymbol(triangle)), legend(lab(1 "EU - 2015") lab(2 "EU - 2016") lab( 3 "EU - 2017") lab(4 "not EU - 2015") lab(5 "not EU - 2016") lab(6 "not EU - 2017")) graphregion(color(white)) ytitle("") xtitle("") title("Exporter KLD (ln) and importer GDP (ln) - HUN")
graph export "output/graph_gdp_d.png", replace
